sudo: false

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages: [libboost-dev, libblocksruntime-dev, clang-5.0, libc++-dev]
        env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      before_script:
        - brew install boost-build

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user codecov

script:
  - clang -v
  - ./build.sh
  - ./test.sh
  - for f in *.c; do gcov -n -o . $f; done
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
